apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: config

resources:
  - namespace.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: house-root-ca
    files:
      - tls.crt=certs/house-root-ca.crt
